@extends('layouts/layoutMaster')

@section('title', 'Monthly Bill Details')


@section('content')
<div class="row">
    <div class="col-12">
        <!-- Bill Header -->
        <div class="card mb-4">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h5 class="mb-0">Monthly Bill Details - #{{ $monthlyBill['id'] }}</h5>
                <div>
                    <!-- Status buttons removed since we don't have status in dynamic bills -->
                    <a href="{{ route('monthly-bills.index') }}" class="btn btn-secondary">
                        <i class="ti ti-arrow-left me-1"></i> Back to List
                    </a>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <table class="table table-striped table-bordered">
                            <tr>
                                <td><strong>Bus:</strong></td>
                                <td>{{ $monthlyBill['bus']->bus_number }} - {{ $monthlyBill['bus']->model_name }}</td>
                            </tr>
                            <tr>
                                <td><strong>Bus Type:</strong></td>
                                <td>
                                    <span class="badge bg-{{ $monthlyBill['bus_type'] == 'hired' ? 'primary' : 'info' }}">
                                        {{ $monthlyBill['bus_type_name'] }}
                                    </span>
                                </td>
                            </tr>
                            <tr>
                                <td><strong>Bill Month:</strong></td>
                                <td>{{ $monthlyBill['formatted_bill_month'] }}</td>
                            </tr>
                            <tr>
                                <td><strong>Period:</strong></td>
                                <td>{{ $monthlyBill['from_date']->format('M d, Y') }} - {{ $monthlyBill['to_date']->format('M d, Y') }}</td>
                            </tr>
                        </table>
                    </div>
                    <div class="col-md-6">
                    <table class="table table-striped table-bordered">
                            <tr>
                                <td><strong>Generated By:</strong></td>
                                <td>System</td>
                            </tr>
                            <tr>
                                <td><strong>Generated At:</strong></td>
                                <td>{{ now()->format('M d, Y H:i A') }}</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <!-- Trip Summary -->
        <div class="row mb-4">
            <div class="col-md-3">
                <div class="card bg-info text-white">
                    <div class="card-body text-center">
                        <h6 class="card-title">Total Trips</h6>
                        <h4 class="mb-0">{{ $monthlyBill['total_trips'] }}</h4>
                        @if($monthlyBill['bus_type'] == 'hired')
                        <small>
                            {{ $monthlyBill['full_days'] }} full days (In+Out)<br>
                            {{ $monthlyBill['half_days'] }} half days (1 trip)
                        </small>
                        @else
                        <small>{{ number_format($monthlyBill['total_distance'], 2) }} KM total distance</small>
                        @endif
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card bg-secondary text-white">
                    <div class="card-body text-center">
                        <h6 class="card-title">Rate</h6>
                        @if($monthlyBill['bus_type'] == 'hired')
                        <h4 class="mb-0">৳{{ number_format($monthlyBill['daily_rate'], 2) }}</h4>
                        <small>per day</small>
                        @else
                        <h4 class="mb-0">৳{{ number_format($monthlyBill['rate_per_km'], 2) }}</h4>
                        <small>per KM</small>
                        @endif
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card bg-primary text-white">
                    <div class="card-body text-center">
                        <h6 class="card-title">Base Amount</h6>
                        <h4 class="mb-0">৳{{ number_format($monthlyBill['base_amount'], 2) }}</h4>
                        @if($monthlyBill['bus_type'] == 'hired')
                        <small>
                            {{ $monthlyBill['full_days'] }} full days (In+Out) × ৳{{ number_format($monthlyBill['daily_rate'], 2) }}<br>
                            {{ $monthlyBill['half_days'] }} half days (1 trip) × ৳{{ number_format($monthlyBill['daily_rate'] / 2, 2) }}
                        </small>
                        @else
                        <small>{{ number_format($monthlyBill['total_distance'], 2) }} KM × ৳{{ number_format($monthlyBill['rate_per_km'], 2) }}</small>
                        @endif
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card bg-success text-white">
                    <div class="card-body text-center">
                        <h6 class="card-title">Total Rewards</h6>
                        <h4 class="mb-0">+৳{{ number_format($monthlyBill['total_rewards'], 2) }}</h4>
                        <small>{{ $rewards->count() }} rewards</small>
                    </div>
                </div>
            </div>
        </div>

        <!-- Financial Summary -->
        <div class="row mb-4">
            <div class="col-md-6">
                <div class="card bg-danger text-white">
                    <div class="card-body text-center">
                        <h6 class="card-title">Total Punishments</h6>
                        <h4 class="mb-0">-৳{{ number_format($monthlyBill['total_punishments'], 2) }}</h4>
                        <small>{{ $punishments->count() }} punishments</small>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card bg-info text-white">
                    <div class="card-body text-center">
                        <h6 class="card-title">Final Amount</h6>
                        <h4 class="mb-0">৳{{ number_format($monthlyBill['final_amount'], 2) }}</h4>
                        <small>After adjustments</small>
                    </div>
                </div>
            </div>
        </div>

        <!-- Trip Details -->
        <div class="card mb-4">
            <div class="card-header">
                <h5 class="mb-0">Trip Details</h5>
            </div>
            <div class="card-body">
                @if($trips->count() > 0)
                <div class="table-responsive">
                <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Date</th>
                                <th>Trip Type</th>
                                <th>Start Stoppage</th>
                                <th>End Stoppage</th>
                                <th>Driver</th>
                                <th>Bus Helper</th>
                                @if($monthlyBill['bus_type'] == 'brtc')
                                <th>Distance (KM)</th>
                                @endif
                                <th>Remarks</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($trips as $trip)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $trip->trip_date->format('M d, Y') }}</td>
                                <td>
                                    <span class="badge bg-{{ $trip->trip_type == 'in' ? 'success' : 'warning' }}">
                                        {{ strtoupper($trip->trip_type) }}
                                    </span>
                                </td>
                                <td>{{ $trip->startStoppage->stoppage_name ?? 'N/A' }}</td>
                                <td>{{ $trip->endStoppage->stoppage_name ?? 'N/A' }}</td>
                                <td>{{ $trip->driver->full_name ?? 'N/A' }}</td>
                                <td>{{ $trip->busHelper->full_name ?? 'N/A' }}</td>
                                @if($monthlyBill['bus_type'] == 'brtc')
                                <td>{{ number_format($trip->total_distance, 2) }}</td>
                                @endif
                                <td>{{ $trip->remarks ?? '-' }}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                @else
                <div class="text-center py-4">
                    <i class="ti ti-calendar-off fs-1 text-muted"></i>
                    <p class="text-muted mt-2">No trip records found for this period</p>
                </div>
                @endif
            </div>
        </div>

        <!-- Rewards Details -->
        @if($rewards->count() > 0)
        <div class="card mb-4">
            <div class="card-header">
                <h5 class="mb-0">Rewards Details</h5>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Date</th>
                                <th>Type</th>
                                <th>Reason</th>
                                <th>Amount</th>
                                <th>Remarks</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($rewards as $reward)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $reward->reward_date->format('M d, Y') }}</td>
                                <td>{{ $reward->rewardType->type_name ?? 'N/A' }}</td>
                                <td>{{ $reward->reason }}</td>
                                <td class="text-success">+৳{{ number_format($reward->reward_amount, 2) }}</td>
                                <td>{{ $reward->remarks ?? '-' }}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        @endif

        <!-- Punishments Details -->
        @if($punishments->count() > 0)
        <div class="card mb-4">
            <div class="card-header">
                <h5 class="mb-0">Punishments Details</h5>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Date</th>
                                <th>Type</th>
                                <th>Violation</th>
                                <th>Description</th>
                                <th>Fine Amount</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($punishments as $punishment)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $punishment->punishment_date->format('M d, Y') }}</td>
                                <td>{{ $punishment->punishmentType->type_name ?? 'N/A' }}</td>
                                <td>{{ $punishment->violationType->type_name ?? 'N/A' }}</td>
                                <td>{{ strlen($punishment->description) > 50 ? substr($punishment->description, 0, 50) . '...' : $punishment->description }}</td>
                                <td class="text-danger">-৳{{ number_format($punishment->fine_amount, 2) }}</td>
                                <td>
                                    <span class="badge bg-{{ $punishment->status == 'active' ? 'warning' : 'success' }}">
                                        {{ ucfirst($punishment->status) }}
                                    </span>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        @endif
    </div>
</div>
@endsection

@push('scripts')
<script>
function updateStatus(billId, status) {
    if (confirm('Are you sure you want to update the bill status?')) {
        fetch(`/app/monthly-bill/${billId}/status`, {
            method: 'PUT',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
            },
            body: JSON.stringify({ status: status })
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                location.reload();
            } else {
                alert('Error updating status: ' + data.message);
            }
        })
        .catch(error => {
            console.error('Error:', error);
            alert('An error occurred while updating the status');
        });
    }
}
</script>
@endpush
