<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Teacher List Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 0;
            padding: 20px;
        }
        
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        
        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #333;
        }
        
        .header p {
            margin: 5px 0 0 0;
            font-size: 14px;
            color: #666;
        }
        
        .report-info {
            margin-bottom: 20px;
            font-size: 11px;
            color: #666;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        
        th, td {
            border: 1px solid #333;
            padding: 8px;
            text-align: left;
            vertical-align: top;
        }
        
        th {
            background-color: #f5f5f5;
            font-weight: bold;
            font-size: 11px;
        }
        
        td {
            font-size: 10px;
        }
        
        .text-center {
            text-align: center;
        }
        
        .text-right {
            text-align: right;
        }
        
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ccc;
            padding-top: 10px;
        }
        
        .no-data {
            text-align: center;
            padding: 20px;
            font-style: italic;
            color: #666;
        }
        
        .page-break {
            page-break-before: always;
        }
        
        .summary {
            margin-bottom: 20px;
            padding: 10px;
            background-color: #f8f9fa;
            border: 1px solid #dee2e6;
            border-radius: 4px;
        }
        
        .summary h3 {
            margin: 0 0 10px 0;
            font-size: 14px;
            color: #333;
        }
        
        .summary p {
            margin: 5px 0;
            font-size: 11px;
        }
        
        .currency {
            text-align: right;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Teacher List Report</h1>
        <p>Generated on: {{ date('F d, Y \a\t h:i A') }}</p>
    </div>
    
    <div class="summary">
        <h3>Report Summary</h3>
        <p><strong>Total Teachers:</strong> {{ $teachers->count() }}</p>
        <p><strong>Report Date:</strong> {{ date('F d, Y') }}</p>
        <p><strong>Generated By:</strong> {{ auth()->user()->name ?? 'System' }}</p>
        
        @if(isset($filters) && (isset($filters['designation_id']) || isset($filters['employee_id'])))
            <h4>Applied Filters:</h4>
            @if(isset($filters['designation_id']) && $filters['designation_id'])
                @php $designation = $designations->find($filters['designation_id']); @endphp
                <p><strong>Designation:</strong> {{ $designation->designation_name ?? 'N/A' }}</p>
            @endif
            @if(isset($filters['employee_id']) && $filters['employee_id'])
                <p><strong>Employee ID:</strong> {{ $filters['employee_id'] }}</p>
            @endif
        @else
            <p><strong>Filters:</strong> All teachers (no filters applied)</p>
        @endif

        @if($teachers->count() > 0)
            @php $designationsGrouped = $teachers->groupBy('designation_id'); @endphp
            <p><strong>Designations in Report:</strong> {{ $designationsGrouped->count() }} different designation(s)</p>
        @endif
    </div>
    
    @if($teachers->count() > 0)
        <table>
            <thead>
                <tr>
                    <th style="width: 5%;">#</th>
                    <th style="width: 10%;">Employee ID</th>
                    <th style="width: 16%;">Teacher Name</th>
                    <th style="width: 14%;">Department</th>
                    <th style="width: 14%;">Designation</th>
                    <th style="width: 18%;">Email</th>
                    <th style="width: 12%;">Phone</th>
                </tr>
            </thead>
            <tbody>
                @foreach($teachers as $index => $teacher)
                    <tr>
                        <td class="text-center">{{ $index + 1 }}</td>
                        <td>{{ $teacher->employee_id }}</td>
                        <td>{{ $teacher->teacher_name }}</td>
                        <td>{{ $teacher->department->name ?? 'N/A' }}</td>
                        <td>{{ $teacher->designation->designation_name ?? 'N/A' }}</td>
                        <td>{{ $teacher->email ?? 'N/A' }}</td>
                        <td>{{ $teacher->phone ?? 'N/A' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="no-data">
            <p>No teachers found matching the criteria.</p>
        </div>
    @endif
    
    <div class="footer">
        <p>This report was generated automatically by the Polytechnic Management System</p>
        <p>For any queries, please contact the administration office</p>
    </div>
</body>
</html>
